spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/products/**
        - id: order-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/orders/**




