spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/cars/**
            - Path=/cars/{id}   # Include the ID path
        - id: order-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/Order/**
